LOCAL_MODULE    := libmplayer
LOCAL_ARM_MODE  := arm
LOCAL_CFLAGS    := -O4 -ffast-math -fomit-frame-pointer -Wall -DOPT_ARM -DHAVE_STRERROR -DHAVE_STDLIB_H -DHAVE_STRDUP -DHAVE_SIGNAL_H -DHAVE_SYS_SIGNAL_H -DHAVE_UNISTD_H -DHAVE_SYS_TYPES_H -DHAVE_INTTYPES_H -DHAVE_STDINT_H -DHAVE_LIMITS_H -DHAVE_STRING_H -DHAVE_SYS_TIME_H -DHAVE_SYS_SELECT_H -DHAVE_ATOLL -DNO_REAL -DNO_8BIT -DNO_32BIT -DNO_NTOM -DREAL_IS_FIXED -funroll-loops


LOCAL_SRC_FILES =   mplayer/mplayer.c	 
LOCAL_LDFLAGS := 
include $(BUILD_SHARED_LIBRARY)
